
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: on-failure
  
  db:
    image: postgres
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  postgres_data: